# Pi dashboard configuration

# system configuration
systemConfig:
  kiosk: false

# global configuration, contains key-value pairs
globalConfig:
  rpcBaseUrl: 'http://your-router-rpc-url'

# component modules list
componentModules:
# item must contains `name` property, 
# the rest properties are configuration key-value pairs merging to global config
  -
    _name: '**YOUR_MODULE_NAME**'
    _tag: '*'
    customConfig1: 'config1'
    customConfig2: 'config2'